language: generic
os: osx
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: change
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
env:
  global:
  - UNITYCI_PROJECT_NAME=""
  - UPLOAD_KEYPATH="./Scripts/upload"